# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField(verbose_name='edit time')),
                ('edit_user', models.CharField(max_length=200)),
                ('edit_content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('report_time', models.IntegerField(default=0)),
                ('zb_name', models.CharField(max_length=200)),
                ('dy_type', models.CharField(max_length=200)),
                ('type_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('id_num', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('birth_area', models.CharField(max_length=200)),
                ('job_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.DateTimeField(verbose_name='last save time')),
                ('submit_time', models.DateTimeField(verbose_name='submit time')),
                ('audit_time', models.DateTimeField(verbose_name='audit time')),
                ('submit_status', models.CharField(max_length=200)),
                ('audit_status', models.CharField(max_length=200)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Infos')),
            ],
        ),
        migrations.AddField(
            model_name='historys',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Infos'),
        ),
    ]
