# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='report_time',
            new_name='上报时间',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='birth_area',
            new_name='党员类别',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='dy_type',
            new_name='姓名',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='gender',
            new_name='性别',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='id_num',
            new_name='支部名称',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='info_id',
            new_name='民族',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='job_class',
            new_name='籍贯',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='type_id',
            new_name='类别编号',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='name',
            new_name='职级',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='nationality',
            new_name='身份证号',
        ),
        migrations.RemoveField(
            model_name='infos',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='infos',
            name='zb_name',
        ),
    ]
