# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170725_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='infos',
            name='info_id',
            field=models.IntegerField(default=0),
        ),
    ]
