# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170804_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='出生年月',
            field=models.DateField(default='1888-11-23'),
        ),
    ]
