# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_infos_出生年月'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='audit_time',
        ),
        migrations.RemoveField(
            model_name='status',
            name='save_time',
        ),
        migrations.RemoveField(
            model_name='status',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='status',
            name='audit time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='create time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='create_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='last save time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='submit time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='audit_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='submit_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
