# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_auto_20170804_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='create_by',
        ),
        migrations.AddField(
            model_name='status',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
