# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20170804_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='info_id',
        ),
    ]
