# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_infos_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.Infos'),
        ),
    ]
