# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20170804_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='create time',
            new_name='create_time',
        ),
    ]
