# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20170804_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='last save time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
