# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20170804_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='last save time',
            new_name='save_time',
        ),
    ]
