# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20170804_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='audit time',
            new_name='audit_time',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='submit time',
            new_name='submit_time',
        ),
        migrations.AlterField(
            model_name='historys',
            name='edit_content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historys',
            name='edit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historys',
            name='edit_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
