# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20170901_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='党员类别',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='姓名',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='性别',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='支部名称',
            field=models.CharField(default='', max_length=200),
        ),
    ]
