# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20170901_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='党员类别',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='出生年月',
            field=models.DateField(blank=True, default='1888-11-23'),
        ),
        migrations.AlterField(
            model_name='infos',
            name='性别',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='支部名称',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='infos',
            name='类别编号',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
