# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 04:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170801_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_level',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
